FROM node:22-alpine

WORKDIR /app

ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}

COPY . .
RUN npm install -g npm@11.7.0
RUN npm install

CMD ["sh", "-c", "npm run build && npm run start"]
